### ISSUE TITLE
Unit Test Frontend

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/pull-requests#18]
My bad on this one - there is no front-end tests anymore

This should be corrected - especially the cells rechunk + chunk/comment matching need desperately tests.

**Comment by bollwyvl** [comment]
Ha, in starting #30, I didn't realize that _all_ of the tests were broken! I'll be just turning them off!

I think _before_ we even do this, we should:
- turn on as many compiler options as possible
  - `strictNullCheck` alone can save many headaches
- increase the aggression of the linter
  - pulling more of the current baseline configuration from core is probably the quickest way

Once we do bring back pure jest _unit_ tests (which invoke no browser), I propose we:

- leverage our JSON Schema from #17
  - ideally with something like [fast-check](https://github.com/dubzzz/fast-check) and [json-schema-fast-check](https://github.com/meeshkan/json-schema-fast-check)
  - this is _massively_ useful at finding corner cases, as getting JSON validation into different parts of the app will cut down on ambiguous data
- move as many operations against data as we can _out_ of react components and their event handlers/didShouldCouldMaybeUnMounts (#19) into discrete, testable functions of manager/model classes which _don't_ require reasoning about the react lifecycle   
- get them under coverage, with a threshold, uploaded to codecov
- only run them linux
  - since they only run in nodejs, we're testing... nodejs. no users will be running server-side node.
  - this can gate heavier browser-based tests

**Comment by bollwyvl** [comment]
Closed by #33
